language: c

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # copied from Rcpp11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.8 libgfortran3-dbg
  - mkdir ~/.R
  - echo -e "CC=gcc-4.9 -std=gnu99\nCXX=g++-4.9 -std=c++11\nnCXX1X=g++-4.9\nCXXFLAGS=-g -O3\nCXX1XFLAGS=-g -O3\nCFLAGS=-g -O3\n" > ~/.R/Makevars

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package richfitz/RcppR6
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:DPfom03G2FgVC9z69XMi9g4L
