language: c

sudo: required

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  # Update C++ compiler to a C++11 compatible one, while still
  # mantaining the ability to link gfortran code.  From:
  # http://gearchicken.com/wordpress/?p=105
  # http://askubuntu.com.80bola.com/questions/612591/usr-bin-ld-cannot-find-lgfortran-matlab
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-4.9 libgfortran3-dbg
  - sudo ln -s /usr/lib/x86_64-linux-gnu/libgfortran.so.3 /usr/lib/x86_64-linux-gnu/libgfortran.so
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 90

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh github_package hadley/testthat
  - ./travis-tool.sh github_package richfitz/RcppR6
  - ./travis-tool.sh github_package smbache/loggr
  - ./travis-tool.sh github_package jimhester/covr

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
  slack: bdkd:DPfom03G2FgVC9z69XMi9g4L
